### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [TheNewco/tncjs-gtm-template#1]
https://github.com/TheNewco/tncjs-gtm-template/blob/def0faa75968441f20578417cee701144a2ecd59/template.tpl#L377C49-L377C111

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by micheletnc** [comment]
Good point, thank you. Fixed!
